project_id = "efdqqnubowgwsnwvlalp"

[functions.chat-with-gpt5]
verify_jwt = false

[functions.update-sky-color]
verify_jwt = false

[functions.generate-3d-model]
verify_jwt = false

[functions.update-reality-settings]
verify_jwt = false